---

- name: Apt-get clean
  ansible.builtin.apt:
    clean: true

- name: Apt-get autoclean
  ansible.builtin.apt:
    autoclean: true

- name: Restart rnsd
  ansible.builtin.service:
    name: rnsd.service
    state: restarted

- name: Restart lxmd
  ansible.builtin.service:
    name: lxmd.service
    state: restarted

- name: Restart nomadnet
  ansible.builtin.service:
    name: nomadnet.service
    state: restarted
